[build]
builder = "nixpacks"
buildCommand = "pip3 install -r telegram-bot/requirements.txt"

[deploy]
startCommand = "python3 telegram-bot/bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
